# -*- coding: utf-8 -*-
"""breast_cancer_wisconsin_diagnostic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CRz8BMcWYYxmmqLfGrSEcmPFMEhG8Fj
"""

import sys
!{sys.executable} -m pip install ucimlrepo

from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
# Convert target variable 'y' to numeric values
from sklearn.preprocessing import LabelEncoder

# fetch dataset
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17)

# data (as pandas dataframes)
X = breast_cancer_wisconsin_diagnostic.data.features
y = breast_cancer_wisconsin_diagnostic.data.targets

# y.replace(['M', 'B'],['0', '1'], inplace=True)

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

sc = StandardScaler()
sc_X_train = sc.fit_transform(X_train)
sc_X_test = sc.transform(X_test)

# Define the FNN model
model = Sequential()

# Add input layer and hidden layers
model.add(Dense(units=128, activation='relu', input_dim=sc_X_train.shape[1]))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))

# Add output layer
model.add(Dense(units=1, activation='sigmoid'))  # Assuming binary classification, adjust units for multiclass

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(sc_X_train, y_train, epochs=50, batch_size=32, validation_data=(sc_X_test, y_test))

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(sc_X_test, y_test)
print(f'Test Loss: {test_loss}, Test Accuracy: {test_accuracy}')